apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-cv-samtale
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /cv-samtale/internal/isAlive
    initialDelay: 20
  readiness:
    path: /cv-samtale/internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
  webproxy: false
  prometheus:
    enabled: false
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: CV_API_URL
      value: {{ cv-api-url }}
    - name: LOGINSERVICE_URL
      value: {{ loginservice }}
    - name: LOGOUTSERVICE_URL
      value: {{ logoutservice }}
    - name: AMPLITUDE_TOKEN
      value: {{ amplitudetoken }}
